const Joi = require("joi");

const createSheetSchema = Joi.object({
  sheetType: Joi.string().max(225).required(),
  boardId: Joi.string().uuid().required(),
  subBoardId: Joi.string().uuid().required(),
  grade: Joi.string().max(225).required(),
  subjectId: Joi.string().uuid().required(),
  subjectLevelId: Joi.string().uuid().required(),
  mypMarkingScheme: Joi.string().max(225).required(),
  answerType: Joi.string().max(225).required(),
  pricingSchForStudents: Joi.string().max(225).required(),
  pricingSchForTeachers: Joi.string().max(225).required(),
  numberOfQuestion: Joi.number().required(),
  timeVariable: Joi.string().max(225).required(),
  questionVedioLink: Joi.string().required(),
  resources: Joi.string(),
  isMCQQuestion: Joi.boolean().required(),
  sheetHintForUploader: Joi.string().required(),
  sheetDescForUploader: Joi.string().required(),
  isMultiplePaperNo: Joi.boolean(),
  year: Joi.string(),
  season: Joi.string(),
  variantId: Joi.string().uuid(),
  school: Joi.string(),
  testType: Joi.string(),
  batchHint: Joi.number(),
  publishTo: Joi.string(),
  assignOn: Joi.string(),
  lifeCycle: Joi.string(),
  supervisorId: Joi.string().uuid().required(),
  uploader2Id: Joi.string().uuid(),
  teacherId: Joi.string().uuid(),
  reviewerId: Joi.string().uuid(),
  assignedToUserId: Joi.string().uuid(),
  statusForSupervisor: Joi.string(),
  statusForUploader: Joi.string(),
  statusForReviewer: Joi.string(),
});

module.exports = { createSheetSchema };
